security:
  jwt:
    token:
      secret-key: eF3AYQPPEE0VTFo86X33gDsYdnCs3ClwcaA7wSL2xgg=

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: timemanagementservice
#          uri: lb://timemanagementservice
#          predicates:
#            - Path=/api/workdays/**
#          filters:
#            - AuthenticationFilter
#
#        - id: useridentityservice
#          uri: lb://useridentityservice
#          predicates:
#            - Path=/api/v1/auth/**